# Generated by Django 4.1.3 on 2024-02-26 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('MCA_60', 'Master of Computer Applications - 60 seats'), ('MTECH_2', 'Master of Technology - 2 seats')], max_length=15)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField(null=True)),
                ('nationality', models.CharField(max_length=100)),
                ('annual_income', models.CharField(blank=True, max_length=100)),
                ('contact_number', models.CharField(max_length=20, null=True)),
                ('alternate_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('address_line1', models.CharField(max_length=30)),
                ('address_line2', models.CharField(max_length=30)),
                ('landmark', models.CharField(max_length=30)),
                ('town_city', models.CharField(max_length=20)),
                ('pincode', models.CharField(max_length=6)),
                ('district', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=30)),
                ('permanent_address', models.BooleanField(default=False)),
                ('bachelor', models.CharField(choices=[('Bsc IT', 'Bsc IT'), ('BCA', 'BCA'), ('OTHER', 'Other')], default='', max_length=10)),
                ('uni', models.CharField(max_length=30)),
                ('place', models.CharField(choices=[('India', 'India'), ('Abroad', 'Abroad')], default='', max_length=30)),
                ('gtype', models.CharField(choices=[('Full time', 'Full time'), ('part time', 'part time')], default='', max_length=30)),
                ('p_year', models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022')], default='', max_length=30)),
                ('gstatus', models.CharField(choices=[('PASSED', 'PASSED'), ('FAILED', 'FAILED')], default='', max_length=30)),
                ('g_marks', models.CharField(choices=[('CGPA', 'CGPA'), ('PERCENT', 'PERCENT')], default='', max_length=30)),
                ('cgpa_marks', models.CharField(default='', max_length=30)),
                ('cgpa_outof', models.CharField(blank=True, default='', max_length=30)),
                ('cgpa_percent', models.CharField(default='', max_length=30)),
                ('ssc_marks', models.CharField(max_length=30)),
                ('ssc_outof', models.CharField(blank=True, max_length=30)),
                ('ssc_percent', models.CharField(blank=True, max_length=30)),
                ('hsc_marks', models.CharField(max_length=30)),
                ('hsc_outof', models.CharField(blank=True, max_length=30)),
                ('hsc_percent', models.CharField(blank=True, max_length=30)),
                ('maths_marks', models.CharField(max_length=30)),
                ('maths_outof', models.CharField(blank=True, max_length=30)),
                ('maths_percent', models.CharField(blank=True, max_length=30)),
                ('science_marks', models.CharField(max_length=30)),
                ('science_outof', models.CharField(blank=True, max_length=30)),
                ('science_percent', models.CharField(blank=True, max_length=30)),
                ('english_marks', models.CharField(max_length=30)),
                ('english_outof', models.CharField(blank=True, max_length=30)),
                ('english_percent', models.CharField(blank=True, max_length=30)),
                ('mahcet_score', models.CharField(blank=True, max_length=20)),
                ('file_tenth', models.FileField(default=None, max_length=250, null=True, upload_to='documents/tenth/')),
                ('file_twelfth', models.FileField(default=None, max_length=250, null=True, upload_to='documents/twelfth/')),
                ('leaving_certificate', models.FileField(default=None, max_length=250, null=True, upload_to='documents/leaving/')),
                ('graduation_marksheet', models.FileField(default=None, max_length=250, null=True, upload_to='documents/graduation/')),
                ('mah_cet_scorecard', models.FileField(default=None, max_length=250, null=True, upload_to='documents/mca_cet/')),
                ('personal_details_completed', models.BooleanField(default=False)),
                ('contact_details_completed', models.BooleanField(default=False)),
                ('address_details_completed', models.BooleanField(default=False)),
                ('qualification_details_completed', models.BooleanField(default=False)),
                ('graduation_details_completed', models.BooleanField(default=False)),
                ('document_details_completed', models.BooleanField(default=False)),
                ('is_submitted', models.BooleanField(default=False)),
                ('app_is_clicked', models.BooleanField(default=False)),
                ('is_accepted', models.CharField(default='Pending', max_length=10)),
                ('remark', models.CharField(blank=True, max_length=100)),
                ('publish_selected_branch', models.CharField(default='', max_length=50, null=True)),
                ('is_declined', models.BooleanField(default=False)),
                ('seat_is_accepted', models.BooleanField(default=False)),
                ('admin_selected_round', models.CharField(default='', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
